# coding: utf-8

"""
    Sonarr

    Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel

class ReleaseEpisodeResource(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    id: Optional[int]
    season_number: Optional[int]
    episode_number: Optional[int]
    absolute_episode_number: Optional[int]
    title: Optional[str]
    __properties = ["id", "seasonNumber", "episodeNumber", "absoluteEpisodeNumber", "title"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True
        alias_generator = lambda x: x.split("_")[0] + "".join(word.capitalize() for word in x.split("_")[1:])

    def __getitem__(self, item):
        return getattr(self, item)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ReleaseEpisodeResource:
        """Create an instance of ReleaseEpisodeResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if absolute_episode_number (nullable) is None
        if self.absolute_episode_number is None:
            _dict['absoluteEpisodeNumber'] = None

        # set to None if title (nullable) is None
        if self.title is None:
            _dict['title'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ReleaseEpisodeResource:
        """Create an instance of ReleaseEpisodeResource from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return ReleaseEpisodeResource.parse_obj(obj)

        _obj = ReleaseEpisodeResource.parse_obj({
            "id": obj.get("id"),
            "season_number": obj.get("seasonNumber"),
            "episode_number": obj.get("episodeNumber"),
            "absolute_episode_number": obj.get("absoluteEpisodeNumber"),
            "title": obj.get("title")
        })
        return _obj

