# coding: utf-8

"""
    Sonarr

    Sonarr API docs  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel
from sonarr.models.season_resource import SeasonResource

class SeasonPassSeriesResource(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    id: Optional[int]
    monitored: Optional[bool]
    seasons: Optional[List]
    __properties = ["id", "monitored", "seasons"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True
        alias_generator = lambda x: x.split("_")[0] + "".join(word.capitalize() for word in x.split("_")[1:])

    def __getitem__(self, item):
        return getattr(self, item)

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SeasonPassSeriesResource:
        """Create an instance of SeasonPassSeriesResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in seasons (list)
        _items = []
        if self.seasons:
            for _item in self.seasons:
                if _item:
                    _items.append(_item.to_dict())
            _dict['seasons'] = _items
        # set to None if monitored (nullable) is None
        if self.monitored is None:
            _dict['monitored'] = None

        # set to None if seasons (nullable) is None
        if self.seasons is None:
            _dict['seasons'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SeasonPassSeriesResource:
        """Create an instance of SeasonPassSeriesResource from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return SeasonPassSeriesResource.parse_obj(obj)

        _obj = SeasonPassSeriesResource.parse_obj({
            "id": obj.get("id"),
            "monitored": obj.get("monitored"),
            "seasons": [SeasonResource.from_dict(_item) for _item in obj.get("seasons")] if obj.get("seasons") is not None else None
        })
        return _obj

